"""
GitHub Webhook Handler for Code Commit Extension
Listens for GitHub webhooks (issues, issue comments), calls local code-assist to write fixes, creates PRs
"""
import hmac
import hashlib
import json
import os
import logging
from datetime import datetime
from typing import Optional

import requests
from flask import Flask, request, jsonify
from sqlalchemy import create_engine, Column, Integer, String, DateTime, Text, Boolean, Enum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import enum

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)

# Database setup
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://codecommit:codecommit@localhost:5432/codecommit")
engine = create_engine(DATABASE_URL)
Session = sessionmaker(bind=engine)
Base = declarative_base()


class IssueStatus(enum.Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    PR_CREATED = "pr_created"
    MERGED = "merged"
    FAILED = "failed"


class Issue(Base):
    __tablename__ = "issues"
    
    id = Column(Integer, primary_key=True)
    github_issue_id = Column(Integer, unique=True)
    repo_full_name = Column(String(100))
    issue_number = Column(Integer)
    issue_title = Column(Text)
    issue_body = Column(Text)
    issue_url = Column(String(500))
    status = Column(Enum(IssueStatus), default=IssueStatus.PENDING)
    pr_url = Column(String(500), nullable=True)
    pr_number = Column(Integer, nullable=True)
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


Base.metadata.create_all(engine)


# Environment variables
GITHUB_WEBHOOK_SECRET = os.getenv("GITHUB_WEBHOOK_SECRET", "")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
CODE_COMMIT_REPO_URL = os.getenv("CODE_COMMIT_REPO_URL", "https://github.com/AGenNext/code-commit")
AUTO_MERGE_ENABLED = os.getenv("AUTO_MERGE_ENABLED", "true").lower() == "true"
CODE_ASSIST_URL = os.getenv("CODE_ASSIST_URL", "http://code-assist:8081")


def verify_signature(payload: bytes, signature: str) -> bool:
    """Verify GitHub webhook signature"""
    if not GITHUB_WEBHOOK_SECRET:
        return True
    expected = hmac.new(
        GITHUB_WEBHOOK_SECRET.encode(),
        payload,
        hashlib.sha256
    ).hexdigest()
    return hmac.compare_digest(f"sha256={expected}", signature)


def get_github_headers():
    """Get headers for GitHub API requests"""
    return {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }


def call_code_assist(issue: Issue) -> dict:
    """
    Call local code-assist to write fix for the issue
    Returns: {"success": bool, "branch": str, "commit_sha": str, "files_changed": list}
    """
    url = f"{CODE_ASSIST_URL}/fix"
    payload = {
        "issue_title": issue.issue_title,
        "issue_body": issue.issue_body,
        "repo_url": issue.issue_url,
    }
    
    try:
        response = requests.post(url, json=payload, timeout=300)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        logger.error(f"Code assist call failed: {e}")
        return {"success": False, "error": str(e)}


def create_pr(issue: Issue, branch: str, commit_sha: str) -> dict:
    """Create a pull request with the fix"""
    repo = issue.repo_full_name
    
    # Get the default branch
    api_url = f"https://api.github.com/repos/{repo}"
    response = requests.get(api_url, headers=get_github_headers())
    response.raise_for_status()
    default_branch = response.json().get("default_branch", "main")
    
    # Create PR
    pr_url = f"https://api.github.com/repos/{repo}/pulls"
    pr_payload = {
        "title": f"Fix: {issue.issue_title}",
        "body": f"""## Fix for Issue #{issue.issue_number}

{issue.issue_body}

**Generated by Code Commit Extension**
- Issue: #{issue.issue_number}
- Branch: {branch}
- Commit: {commit_sha}
""",
        "head": branch,
        "base": default_branch,
    }
    
    response = requests.post(pr_url, json=pr_payload, headers=get_github_headers())
    response.raise_for_status()
    pr_data = response.json()
    
    return {
        "url": pr_data.get("html_url"),
        "number": pr_data.get("number"),
        "head_sha": commit_sha
    }


def check_and_merge_pr(issue: Issue) -> bool:
    """
    Check if PR tests pass and auto-merge if enabled
    """
    if not AUTO_MERGE_ENABLED:
        return False
    
    repo = issue.repo_full_name
    pr_number = issue.pr_number
    
    # Check PR status
    status_url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}"
    response = requests.get(status_url, headers=get_github_headers())
    response.raise_for_status()
    pr_data = response.json()
    
    # Check if mergeable
    if not pr_data.get("mergeable"):
        return False
    
    # Check if all checks passed
    checks_url = f"https://api.github.com/repos/{repo}/commits/{pr_data.get('head', {}).get('sha')}/status"
    response = requests.get(checks_url, headers=get_github_headers())
    if response.status_code == 200:
        status_data = response.json()
        if status_data.get("state") != "success":
            return False
    
    # Merge the PR
    merge_url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}/merge"
    merge_payload = {
        "merge_method": "squash"
    }
    
    response = requests.put(merge_url, json=merge_payload, headers=get_github_headers())
    if response.status_code == 200:
        logger.info(f"Merged PR #{pr_number}")
        return True
    
    return False


@app.route("/webhook", methods=["POST"])
def handle_webhook():
    """Handle GitHub webhook events"""
    # Verify signature
    signature = request.headers.get("X-Hub-Signature-256", "")
    if not verify_signature(request.data, signature):
        return jsonify({"error": "Invalid signature"}), 401
    
    event = request.headers.get("X-GitHub-Event", "")
    payload = request.json
    
    logger.info(f"Received event: {event}")
    
    if event == "issues":
        return handle_issue_event(payload)
    elif event == "issue_comment":
        return handle_issue_comment_event(payload)
    elif event == "pull_request":
        return handle_pull_request_event(payload)
    
    return jsonify({"status": "ignored"})


def handle_issue_event(payload: dict) -> jsonify:
    """Handle issue opened event"""
    action = payload.get("action")
    if action not in ("opened", "reopened"):
        return jsonify({"status": "ignored"})
    
    issue = payload.get("issue", {})
    repo = payload.get("repository", {})
    
    # Check for auto-fix label or keyword
    labels = issue.get("labels", [])
    title = issue.get("title", "").lower()
    
    should_fix = False
    for label in labels:
        if label.get("name", "").lower() in ("auto-fix", "fix-me", "bug"):
            should_fix = True
            break
    
    # Also trigger on keywords in title
    if any(keyword in title for keyword in ("fix", "bug", "error", "broken")):
        should_fix = True
    
    if not should_fix:
        return jsonify({"status": "no auto-fix triggered"})
    
    # Store issue in database
    session = Session()
    try:
        db_issue = Issue(
            github_issue_id=issue.get("id"),
            repo_full_name=repo.get("full_name"),
            issue_number=issue.get("number"),
            issue_title=issue.get("title"),
            issue_body=issue.get("body"),
            issue_url=issue.get("html_url"),
            status=IssueStatus.PENDING
        )
        session.add(db_issue)
        session.commit()
        
        # Call local code-assist
        result = call_code_assist(db_issue)
        
        if result.get("success"):
            db_issue.status = IssueStatus.PROCESSING
            
            # Create PR
            pr_result = create_pr(
                db_issue,
                result.get("branch"),
                result.get("commit_sha")
            )
            
            db_issue.pr_url = pr_result.get("url")
            db_issue.pr_number = pr_result.get("number")
            db_issue.status = IssueStatus.PR_CREATED
            session.commit()
            
            # Comment on issue
            comment_url = f"https://api.github.com/repos/{repo.get('full_name')}/issues/{issue.get('number')}/comments"
            comment_payload = {
                "body": f"""## Fix Generated! 🎉

I've created a pull request to fix this issue: {pr_result.get('url')}

The fix will be automatically merged once all checks pass.
"""
            }
            requests.post(comment_url, json=comment_payload, headers=get_github_headers())
            
            return jsonify({"status": "pr_created", "pr_url": pr_result.get("url")})
        else:
            db_issue.status = IssueStatus.FAILED
            db_issue.error_message = result.get("error")
            session.commit()
            return jsonify({"status": "failed", "error": result.get("error")}), 500
            
    except Exception as e:
        logger.error(f"Error handling issue: {e}")
        session.rollback()
        return jsonify({"error": str(e)}), 500
    finally:
        session.close()


def handle_issue_comment_event(payload: dict) -> jsonify:
    """Handle issue comment event - trigger on /fix command"""
    action = payload.get("action")
    if action != "created":
        return jsonify({"status": "ignored"})
    
    comment = payload.get("comment", {})
    body = comment.get("body", "").strip()
    
    # Check for /fix command
    if not body.lower().startswith("/fix"):
        return jsonify({"status": "not a fix command"})
    
    issue = payload.get("issue", {})
    repo = payload.get("repository", {})
    
    # Store issue in database
    session = Session()
    try:
        db_issue = Issue(
            github_issue_id=issue.get("id"),
            repo_full_name=repo.get("full_name"),
            issue_number=issue.get("number"),
            issue_title=issue.get("title"),
            issue_body=issue.get("body"),
            issue_url=issue.get("html_url"),
            status=IssueStatus.PENDING
        )
        session.add(db_issue)
        session.commit()
        
        # Call local code-assist
        result = call_code_assist(db_issue)
        
        if result.get("success"):
            db_issue.status = IssueStatus.PROCESSING
            
            # Create PR
            pr_result = create_pr(
                db_issue,
                result.get("branch"),
                result.get("commit_sha")
            )
            
            db_issue.pr_url = pr_result.get("url")
            db_issue.pr_number = pr_result.get("number")
            db_issue.status = IssueStatus.PR_CREATED
            session.commit()
            
            return jsonify({"status": "pr_created", "pr_url": pr_result.get("url")})
        else:
            db_issue.status = IssueStatus.FAILED
            db_issue.error_message = result.get("error")
            session.commit()
            return jsonify({"status": "failed"}), 500
            
    except Exception as e:
        logger.error(f"Error handling comment: {e}")
        session.rollback()
        return jsonify({"error": str(e)}), 500
    finally:
        session.close()


def handle_pull_request_event(payload: dict) -> jsonify:
    """Handle pull request events - check and merge if enabled"""
    action = payload.get("action")
    pr = payload.get("pull_request", {})
    repo = payload.get("repository", {})
    
    # Only handle "opened" to check status
    if action != "opened":
        return jsonify({"status": "ignored"})
    
    # Check if this PR is from our bot
    user = pr.get("user", {})
    if user.get("login") != "code-commit[bot]":
        return jsonify({"status": "not our pr"})
    
    # Check and merge
    session = Session()
    try:
        issue = session.query(Issue).filter_by(pr_number=pr.get("number")).first()
        if issue and AUTO_MERGE_ENABLED:
            merged = check_and_merge_pr(issue)
            if merged:
                issue.status = IssueStatus.MERGED
                session.commit()
                return jsonify({"status": "merged"})
        
        return jsonify({"status": "checks pending"})
    finally:
        session.close()


@app.route("/health", methods=["GET"])
def health_check():
    """Health check endpoint"""
    return jsonify({"status": "healthy"})


@app.route("/issues", methods=["GET"])
def list_issues():
    """List tracked issues"""
    session = Session()
    try:
        issues = session.query(Issue).order_by(Issue.created_at.desc()).limit(50).all()
        return jsonify([{
            "id": i.id,
            "repo": i.repo_full_name,
            "issue_number": i.issue_number,
            "title": i.issue_title,
            "status": i.status.value,
            "pr_url": i.pr_url,
            "created_at": i.created_at.isoformat()
        } for i in issues])
    finally:
        session.close()


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)